// <auto-generated />
using System;
using DoubleVPartnersAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoubleVPartnersAPI.Migrations
{
    [DbContext(typeof(DoubleVPartnersContext))]
    partial class DoubleVPartnersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoubleVPartnersAPI.Models.TKS_TICKETS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ESTADO")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FECHA_ACTUALIZACION")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FECHA_CREACION")
                        .HasColumnType("datetime2");

                    b.Property<string>("USUARIO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TKS_TICKETS");
                });
#pragma warning restore 612, 618
        }
    }
}
